apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ourglass-cacerts-job
  namespace: ourglass-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: ourglass-cacerts-job
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-demo-fabric
        namespace: flux-demo-fabric
      chart: platforms/hyperledger-fabric/charts/generate_cacerts
  values:
    metadata:
      name: ourglass
      component_name: ourglass-net
      namespace: ourglass-net    
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    vault:
      role: vault-role
      address: http://35.223.173.61:8200
      authpath: demo-fabricourglass-net-auth
      secretcryptoprefix: secretsv2/data/crypto/ordererOrganizations/ourglass-net/ca
      secretcredentialsprefix: secretsv2/data/credentials/ourglass-net/ca/ourglass
      serviceaccountname: vault-auth
      imagesecretname: regcred
      
    ca:
      subject: /C=GB/ST=London/L=London/O=Orderer/CN=ca.ourglass-net
