apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ourglassorg2-restserver
  namespace: ourglassorg2-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: ourglassorg2-restserver
  interval: 1m
  chart:
   spec:
    chart: examples/supplychain-app/charts/fabric-restserver
    sourceRef:
      kind: GitRepository
      name: flux-demo-fabric
      namespace: flux-demo-fabric
  values:
    metadata:
      namespace: ourglassorg2-net
    server:
      name: ourglassorg2-restserver
      port: 20001
      localmspid: ourglassorg2MSP
      image: index.docker.io/joseucarvajal/bevel-supplychain-fabric:rest-server-stable
      username: admin
      cert_path: "/secret/tls/admin.cert"
      key_path: "/secret/tls/admin.pem"
    storage:
      storageclassname: ourglassorg2sc
      storagesize: 512Mi
    vault:
      address: http://104.154.176.16:8200
      role: vault-role
      authpath: demo-fabricourglassorg2-net-auth
      secretprefix: secretsv2/data/crypto/peerOrganizations/ourglassorg2-net
      serviceaccountname: vault-auth
      imagesecretname: regcred
      image: ghcr.io/hyperledger/alpine-utils:1.0
    service:
      servicetype: ClusterIP
      ports:
        apiPort: 20001
        targetPort: 8000
    connection:
      peer: peer1.ourglassorg2-net
      peerAddress: peer1.ourglassorg2-net
      peerPort: 7051
      ordererAddress: orderer0.ourglass.com
      ordererPort: 443
