apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ourglassorg2-peer1
  namespace: ourglassorg2-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: ourglassorg2-peer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-demo-fabric
        namespace: flux-demo-fabric
      chart: platforms/hyperledger-fabric/charts/peernode    
  values:
    metadata:
      namespace: ourglassorg2-net
      images:
        couchdb: couchdb:3.1
        peer: hyperledger/fabric-peer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        
    peer:
      name: peer1
      gossippeeraddress: peer1.ourglassorg2-net:7051
      gossipexternalendpoint: peer1.ourglassorg2-net.ourglass.com:8443
      localmspid: ourglassorg2MSP
      loglevel: info
      tlsstatus: true
      builder: hyperledger/fabric-ccenv:2.2.2
      couchdb:
        username: ourglassorg2-user

    storage:
      peer:
        storageclassname: ourglassorg2sc
        storagesize: 512Mi
      couchdb:
        storageclassname: ourglassorg2sc
        storagesize: 1Gi

    vault:
      role: vault-role
      address: http://104.154.176.16:8200
      authpath: demo-fabricourglassorg2-net-auth
      secretprefix: secretsv2/data/crypto/peerOrganizations/ourglassorg2-net/peers/peer1.ourglassorg2-net
      secretambassador: secretsv2/data/crypto/peerOrganizations/ourglassorg2-net/ambassador
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretcouchdbpass: secretsv2/data/credentials/ourglassorg2-net/couchdb/ourglassorg2?user

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7051
        events:
          clusteripport: 7053
        couchdb:
          clusteripport: 5984
          
    proxy:
      provider: "haproxy"
      external_url_suffix: ourglass.com

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
