apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ourglassorg0-net-ca
  namespace: ourglassorg0-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: ourglassorg0-net-ca
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-demo-fabric
        namespace: flux-demo-fabric
      chart: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: ourglassorg0-net
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.8
 
    server:
      name: ca
      tlsstatus: true
      admin: ourglassorg0-admin 
  
    storage:
      storageclassname: ourglassorg0sc
      storagesize: 512Mi
    vault:
      role: vault-role
      address: http://130.211.192.245:8200
      authpath: demo-fabricourglassorg0-net-auth
      secretcert: secretsv2/data/crypto/peerOrganizations/ourglassorg0-net/ca?ca.ourglassorg0-net-cert.pem
      secretkey: secretsv2/data/crypto/peerOrganizations/ourglassorg0-net/ca?ourglassorg0-net-CA.key
      secretadminpass: secretsv2/data/credentials/ourglassorg0-net/ca/ourglassorg0?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: haproxy
      type: peer
      external_url_suffix: ourglass.com
