apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: channel-ourglassorg0-allchannel
  namespace: ourglassorg0-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: channel-ourglassorg0-allchannel
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-demo-fabric
        namespace: flux-demo-fabric
      chart: platforms/hyperledger-fabric/charts/create_channel   
  values:
    metadata:
      namespace: ourglassorg0-net
      network:
        version 2.2.2
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.ourglassorg0-net:7051
      localmspid: ourglassorg0MSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://130.211.192.245:8200
      authpath: demo-fabricourglassorg0-net-auth
      adminsecretprefix: secretsv2/data/crypto/peerOrganizations/ourglassorg0-net/users/admin
      orderersecretprefix: secretsv2/data/crypto/peerOrganizations/ourglassorg0-net/orderer 
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel
    orderer:
      address: orderer0.ourglass.com:443
    channeltx: |-
      CooEChgKFggCGgYItKyymQYiCmFsbGNoYW5uZWwS7QMK6gMKCmFsbGNoYW5uZWwSYBJOCgtBcHBs
      aWNhdGlvbhI/EhMKD291cmdsYXNzb3JnMU1TUBIAEhMKD291cmdsYXNzb3JnMk1TUBIAEhMKD291
      cmdsYXNzb3JnME1TUBIAGg4KCkNvbnNvcnRpdW0SABr5AhLQAgoLQXBwbGljYXRpb24SwAIIARIT
      Cg9vdXJnbGFzc29yZzFNU1ASABITCg9vdXJnbGFzc29yZzJNU1ASABITCg9vdXJnbGFzc29yZzBN
      U1ASABokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5zIiwKC0VuZG9yc2VtZW50
      Eh0SEwgDEg8KC0VuZG9yc2VtZW50EAIaBkFkbWlucyI1ChRMaWZlY3ljbGVFbmRvcnNlbWVudBId
      EhMIAxIPCgtFbmRvcnNlbWVudBACGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJz
      GgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgS
      DggDEgoKBkFkbWlucxACGgZBZG1pbnMqBkFkbWlucxokCgpDb25zb3J0aXVtEhYSFAoST3VyZ2xh
      c3NDb25zb3J0aXVt