apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: joinchannel-peer0-join-allchannel-ourglassorg0-peer0
  namespace: ourglassorg0-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: joinchannel-peer0-join-allchannel-ourglassorg0-peer0
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-demo-fabric
        namespace: flux-demo-fabric
      chart: platforms/hyperledger-fabric/charts/join_channel
  values:
    metadata:
      namespace: ourglassorg0-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.ourglassorg0-net.ourglass.com:443
      localmspid: ourglassorg0MSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://130.211.192.245:8200
      authpath: demo-fabricourglassorg0-net-auth
      adminsecretprefix: secretsv2/data/crypto/peerOrganizations/ourglassorg0-net/users/admin
      orderersecretprefix: secretsv2/data/crypto/peerOrganizations/ourglassorg0-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer0.ourglass.com:443
