apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ourglassorg0-peer0
  namespace: ourglassorg0-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: ourglassorg0-peer0
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-demo-fabric
        namespace: flux-demo-fabric
      chart: platforms/hyperledger-fabric/charts/peernode    
  values:
    metadata:
      namespace: ourglassorg0-net
      images:
        couchdb: couchdb:3.1
        peer: hyperledger/fabric-peer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        
    peer:
      name: peer0
      gossippeeraddress: peer0.ourglassorg0-net:7051
      gossipexternalendpoint: peer0.ourglassorg0-net.ourglass.com:8443
      localmspid: ourglassorg0MSP
      loglevel: info
      tlsstatus: true
      builder: hyperledger/fabric-ccenv:2.2.2
      couchdb:
        username: ourglassorg0-user

    storage:
      peer:
        storageclassname: ourglassorg0sc
        storagesize: 512Mi
      couchdb:
        storageclassname: ourglassorg0sc
        storagesize: 1Gi

    vault:
      role: vault-role
      address: http://130.211.192.245:8200
      authpath: demo-fabricourglassorg0-net-auth
      secretprefix: secretsv2/data/crypto/peerOrganizations/ourglassorg0-net/peers/peer0.ourglassorg0-net
      secretambassador: secretsv2/data/crypto/peerOrganizations/ourglassorg0-net/ambassador
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretcouchdbpass: secretsv2/data/credentials/ourglassorg0-net/couchdb/ourglassorg0?user

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7051
        events:
          clusteripport: 7053
        couchdb:
          clusteripport: 5984
          
    proxy:
      provider: "haproxy"
      external_url_suffix: ourglass.com

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
